[site]
bucket = "./"
entry-point = "."

[build]
command = ""
upload.format = "directory"

# Production environment (main branch)
[env.production]
name = "solemare-apartment"
workers_dev = true
compatibility_date = "2025-05-28"

# Preview environment (all other branches)
[env.preview]
name = "solemare-apartment-preview"
workers_dev = true
compatibility_date = "2025-05-28"

[vars]
# IMPORTANT: These are just placeholders. Do not add actual values here.
# Set the real values in Cloudflare Pages dashboard for each environment:
# 1. Go to your project in Cloudflare Pages
# 2. Click Settings > Environment variables
# 3. Add each variable with its actual value for both production and preview
# 4. Never commit actual API keys or sensitive values to the repository

# Google Maps API key for location and maps features
GOOGLE_MAPS_API_KEY = ""

# Google Calendar ID for availability calendar
GOOGLE_CALENDAR_ID = ""

# Formspree form ID for contact form
FORMSPREE_ID = ""

# OpenWeatherMap API key for weather widget (future use)
OPENWEATHERMAP_API_KEY = ""

# Add any other environment variables here 