name: Quality Check and Deploy

on:
  push:
    branches:
      - preview
      - main
  pull_request:
    branches:
      - main
      - preview
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Code Quality & Security
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund
          npm install --save-dev --no-audit --no-fund --legacy-peer-deps html-validate stylelint stylelint-config-standard eslint@8.56.0 eslint-config-standard@17.1.0

      # HTML validation
      - name: HTML Validation
        run: npx html-validate index.html

      # CSS validation
      - name: CSS Validation
        run: |
          npx stylelint "src/**/*.css" "src/**/*.jsx" --fix
          npx stylelint "src/**/*.css" "src/**/*.jsx"

      # JavaScript validation
      - name: JavaScript Validation
        run: |
          npx eslint "src/**/*.{js,jsx}" --fix
          npx eslint "src/**/*.{js,jsx}"

  deploy-preview:
    # needs: quality
    if: github.ref == 'refs/heads/preview' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'preview')
    runs-on: ubuntu-latest
    name: Deploy Preview
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Cloudflare Pages (Preview) 🔥
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: solemare-apartment
          directory: ./
          wranglerVersion: '3'
          branch: preview
        id: deploy

      - name: Install Chrome dependencies
        run: |
          apt-get update
          apt-get install -y \
            libglib2.0-0 \
            libnss3 \
            libnspr4 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libasound2 \
            libpango-1.0-0 \
            libcairo2 \
            libatspi2.0-0

      - name: Run accessibility tests
        run: |
          npm install --save-dev --no-audit --no-fund axe-core puppeteer
          echo ">> Checking accessibility on preview environment: ${{ steps.deploy.outputs.url }} <<"
          PREVIEW_URL=${{ steps.deploy.outputs.url }} node scripts/accessibility-test.js

      - name: Show Nicolas Cage on failure 🎭
        if: failure()
        run: |
          echo "::error::Pipeline failed! Here's Nicolas Cage to cheer you up:"
          cat public/cage.txt

  deploy-production:
    needs: quality
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Cloudflare Pages (Production) 🎉
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: solemare-apartment
          directory: ./
          wranglerVersion: '3'
          branch: main 