name: Create Release on Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write # Grant write permissions for contents to allow pushing tags and creating releases

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git tagging

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use your preferred Node.js version

      - name: Get package version
        id: get_version
        run: |
          VERSION_NUMBER=$(node -e "console.log(require('./package.json').version)")
          echo "VERSION=$VERSION_NUMBER" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          TAG_NAME=v${{ steps.get_version.outputs.VERSION }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true # Automatically generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 